/*
 * This source file was generated by the Gradle 'init' task
 */
package ds.lab.activity;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void testLinkedListOutput() {
        LinkedList list = new LinkedList();

        
        System.out.println("Test insert at Beggining: 20, 10");
        list.insertAtBeginning(20);
        list.insertAtBeginning(10);
        assertTrue(list.search(10));
        assertTrue(list.search(20));

        System.out.println("Test Insert at End: 30, 40");
        list.insertAtEnd(30);
        list.insertAtEnd(40);
        assertTrue(list.search(30));
        assertTrue(list.search(40));

        System.out.println("Test Search 30");
        boolean found30 = list.search(30);
        System.out.println(found30);
        assertTrue(found30);

        System.out.println("Test Delete 20");
        list.delete(20);
        assertFalse(list.search(20));
        
        System.out.println("Test Delete 10");
        list.delete(10);
        assertFalse(list.search(10));

        System.out.println("Test Search 100");
        boolean found100 = list.search(100);
        System.out.println(found100);
        assertFalse(found100);
    }
}