/*
 * This source file was generated by the Gradle 'init' task
 */
package ds.lab.activity;

public class App {
public static void main(String[] args) {
    LinkedList list = new LinkedList();

    System.out.println("Insert at Beginning: 20, 10");
    list.insertAtBeginning(20);
    list.insertAtBeginning(10);
    list.display();

    System.out.println("Insert at end: 30, 40");
    list.insertAtEnd(30);
    list.insertAtEnd(40);
    list.display();

    System.out.println("Search for 30:");
    System.out.println(list.search(30));

    System.out.println("Delete 20:");
    list.delete(20);
    list.display();
    
    System.out.println("Delete 10:");
    list.delete(10);
    list.display();

    System.out.println("Search for 100:");
    System.out.println(list.search(100));
}
}